name: flutter_auth
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  google_fonts: ^0.2.0
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.6
  provider: ^3.0.0
  smooth_page_indicator: 0.2.0
  flushbar: 1.10.4
  circular_bottom_navigation: ^1.0.1
  font_awesome_flutter: ^8.4.0
  flutter_custom_clippers: ^0.1.6
  html_unescape: ^1.0.1+2
  auto_size_text: ^2.0.0+2
  flutter_dialogflow: ^0.1.3
  bubble: ^1.1.9+1
  table_calendar:
  sqflite:
  intl:
  fl_chart: ^0.12.0
  json_model:
  bezier_chart: ^1.0.16
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.19.1
  charts_flutter: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/undraw_pilates_gpdb.png
    - assets/images/test2.png
    - assets/images/meditation_1.jpg
    - assets/images/chat2.jpg
    - assets/images/testing.jpg
    - assets/images/icon.jpg
    - assets/images/mm1.jpg
    - assets/images/q1.png
    - assets/icons/notification.svg
    - assets/icons/back.svg
    - assets/icons/cart_with_item.svg
    - assets/icons/chat.svg
    - assets/icons/back.svg
    - assets/images/Item_1.png
    - assets/images/Item_2.png
    - assets/images/Item_3.png
    - assets/images/game1.jpg
    - assets/images/mm3.png
    - assets/images/q4.png
    - assets/images/chat5.jpg
    - assets/question.png
    - assets/fox.png
    - assets/fox.png
    - assets/horse.png
    - assets/monkey.png
    - assets/panda.png
    - assets/parrot.png
    - assets/rabbit.png
    - assets/zoo.png
    - assets/smartEEG-14a4fffe134b.json
    - assets/robot.png
    - assets/robot.jpg
    - assets/camera.png
    - assets/default.jpg
    - assets/ilikeit.json
    - assets/images/icon.jpg
    - assets/images/doc2.jpg
    - assets/images/p1.jpg
    - assets/images/w1.jpg
    - assets/icons/notification.svg
    - assets/chart_data.json
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
